language: go

go:
  - 1.5.4
  - 1.6.3

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  # Enable once we scrub the code to fix lint errors
  #- 'golint ./...'
  - go tool vet -test .
  - scripts/coverage --coveralls
